version: '2.4'

services:
  ticklet:
    image: samuelebistoletti/docker-statsd-influxdb-grafana:latest
    ports:
      - 3003:3003 
      - 3004:8888 
      - 8086:8086 
      - 8125:8125/udp
    ulimits:
      nofile:
        soft: "66000"
        hard: "66000"
    volumes:
      - ${PWD}/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - ${PWD}/grafana/provisioning:/etc/grafana/provisioning
      - ${PWD}/grafana/dashboards:/var/lib/grafana/dashboards
      - ${PWD}/grafana/grafana.ini:/etc/grafana/grafana.ini